// <auto-generated />
namespace CourtCases_Harkomal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class iniiit1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iniiit1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110112213548_iniiit1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
